I am process 30857, running on gpu06: starting (Sat Mar  5 11:18:24 2022)
args.batch_size 8
args Namespace(a_imagenet_pretrain=True, a_patch_num=256, audioset_pretrain=False, bal=None, batch_size=8, data_eval='test_iemocap_dataset.json', data_train='train_iemocap_dataset.json', data_val='valid_iemocap_dataset.json', dataset='iemocap', early_stop=5, exp_dir='model_dir/temp_imagenet_8_0.0001_40_fusion', face_size=128, freqm=0, fstride=16, k=-1, label_csv='', lr=0.0001, lr_patience=2, mixup=0, modal='tav', model='ast_models_video_deit', n_class=6, n_epochs=40, n_print_steps=100, num_height=384, num_width=384, num_workers=12, optim='adam', save_model=None, scale=0, seed=1234, text_lr_factor=100, text_max_len=300, time_dim_split=True, timem=0, tstride=16, v_imagenet_pretrain=True, v_patch_num=256)
now process iemocap
---------------the train dataloader---------------
number of classes is 6
now process iemocap
---------------the evaluation dataloader---------------
number of classes is 6
Creating experiment directory: model_dir/temp_imagenet_8_0.0001_40_fusion
Now starting training for 40 epochs
Traceback (most recent call last):
  File "run.py", line 277, in <module>
    train(mt_model, train_loader, val_loader, args, tokenizer_model)
NameError: name 'mt_model' is not defined